import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["vietnamese"] });

export const metadata = {
  title: "KanBan App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <p>sk</p>
        {children} <p>gr</p>
      </body>
    </html>
  );
}
